<script setup lang="ts">
import { PRACTICE_AUTHOR, PRACTICE_MODEL_ID } from '@/practice'

defineProps<{ compact?: boolean }>()
</script>

<template>
  <aside
    class="card border-l-4 border-l-signal-500 p-3 text-sm sm:p-4"
    aria-label="Who wrote these practice exams"
  >
    <p class="font-semibold">
      Written by {{ PRACTICE_AUTHOR }}, an AI model made by Anthropic
      <span class="font-mono text-xs font-normal text-ink-500 dark:text-ink-400">
        ({{ PRACTICE_MODEL_ID }})
      </span>
    </p>
    <p v-if="!compact" class="mt-1 text-ink-600 dark:text-ink-300">
      Unlike the rest of The Runbook, these practice exams were not written by hand. Every
      question, answer and explanation was generated by {{ PRACTICE_AUTHOR }} from pages on
      learn.microsoft.com, and every question links the pages it was drawn from. They are not
      official Microsoft exam content and they are not endorsed by Microsoft. AI-written material
      can be wrong: when an answer surprises you, the linked source is the authority, not the
      explanation.
    </p>
    <p v-else class="mt-1 text-ink-600 dark:text-ink-300">
      Generated from learn.microsoft.com, not official Microsoft content. When an answer surprises
      you, trust the linked source over the explanation.
    </p>
  </aside>
</template>
