# Generated by Django 5.2.17 on 2026-08-24 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('type', models.CharField(choices=[('quest_start', 'Quest started'), ('quest_complete', 'Quest completed'), ('encounter_resolve', 'Encounter resolved'), ('choice', 'Choice made'), ('pip', 'Reputation hit zero'), ('perk_buy', 'Perk purchased')], db_index=True, max_length=40)),
                ('quest_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('encounter_id', models.CharField(blank=True, max_length=64)),
                ('outcome', models.CharField(blank=True, max_length=40)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'analytics event',
                'indexes': [models.Index(fields=['type', 'created_at'], name='analytics_a_type_a70189_idx')],
            },
        ),
    ]
