# Generated by Django 5.2.17 on 2026-08-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_alter_analyticsevent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticsevent',
            name='type',
            field=models.CharField(choices=[('quest_start', 'Quest started'), ('quest_complete', 'Quest completed'), ('encounter_resolve', 'Encounter resolved'), ('choice', 'Choice made'), ('pip', 'Reputation hit zero'), ('perk_buy', 'Perk purchased'), ('act_opened', 'Act opened without finishing the one before'), ('post_mortem', 'Post-mortem answered'), ('review_start', 'Review drill started'), ('review_complete', 'Review drill completed')], db_index=True, max_length=40),
        ),
    ]
