# Generated by Django 5.2.17 on 2026-08-24 07:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaveGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.PositiveIntegerField(default=1)),
                ('blob', models.JSONField(default=dict)),
                ('client_updated_at', models.DateTimeField(help_text='When the browser last wrote this save. Drives last-write-wins.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='savegame', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'save game',
            },
        ),
    ]
