# Generated by Django 5.2.17 on 2026-08-25 03:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('anonymous_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('category', models.CharField(choices=[('confusing', 'Confusing scenario or screen'), ('wrong', 'Technically wrong'), ('bug', 'Something is broken'), ('layout', 'Looks wrong on my screen'), ('idea', 'Suggestion'), ('praise', 'This worked well')], db_index=True, max_length=24)),
                ('message', models.TextField(blank=True)),
                ('route', models.CharField(blank=True, db_index=True, max_length=200)),
                ('quest_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('encounter_id', models.CharField(blank=True, max_length=64)),
                ('content_version', models.CharField(blank=True, max_length=32)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Where the player was and what state they were in.')),
                ('handled', models.BooleanField(db_index=True, default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'feedback',
                'verbose_name_plural': 'feedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['category', 'created_at'], name='feedback_fe_categor_5c7726_idx')],
            },
        ),
    ]
